config/routes.rb
Rails.application.routes.draw do
	get 'pedidos/reporte'
	root 'pedidos#index'
	resources :pedidos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pedido.rb
class Pedido < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: [:show, :edit, :update, :destroy]

  # GET /pedidos
  # GET /pedidos.json
  def index
    @pedidos = Pedido.all
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
  

  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: 'Pedido was successfully created.' }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1
  # PATCH/PUT /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to @pedido, notice: 'Pedido was successfully updated.' }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @pedido.destroy
    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: 'Pedido was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def reporte
  @pedido1 = Pedido.all 
  @CantidadDePlatillos = @pedido1.sort_by(&:CantidadDePlatillos)
  @CantidadDePostres = @pedido1.sort_by(&:CantidadDePostres)
  @CantidadDeBebidas = @pedido1.sort_by(&:CantidadDeBebidas)
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedido_params
      params.require(:pedido).permit(:platillos, :bebidas, :precio, :CantidadDePlatillos, :CantidadDeBebidas, :postre, :CantidadDePostres)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/layouts/application.html.erb
</html>
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Theme Made By www.w3schools.com - No Copyright -->

    <title>Restaurant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <title>Bootstrap Theme Simply Me</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  .bg-1 { 
      background-color: #1abc9c;
      color: #ffffff;
  }
  .bg-2 { 
      background-color: #474e5d;
      color: #ffffff;
  }
  .bg-3 { 
      background-color: #ffffff;
      color: #555555;
  }
  .container-fluid {
      padding-top: 70px;
      padding-bottom: 70px;
  }
  </style>
</head>
<body>

<div class="container-fluid bg-1 text-center">
  <h3>Espinoza</h3>
  



 <img src="http://www.inchina.co/html/data1/images/camarones_in_china.jpg"> 
  <h3>PLATILLOS</h3>
</div>



<div class="container-fluid bg-3 text-center">
  <%= yield %>
</div>

</body>
</html>

app/views/pedidos/_form.html.erb
<%= form_with(model: pedido, local: true) do |form| %>
  <% if pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

      <ul>
      <% pedido.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :platillos %>
    <%= form.text_field :platillos, id: :pedido_platillos %>
  </div>

  <div class="field">
    <%= form.label :bebidas %>
    <%= form.text_field :bebidas, id: :pedido_bebidas %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.number_field :precio, id: :pedido_precio %>
  </div>

  <div class="field">
    <%= form.label :CantidadDePlatillos %>
    <%= form.number_field :CantidadDePlatillos, id: :pedido_CantidadDePlatillos %>
  </div>

  <div class="field">
    <%= form.label :CantidadDeBebidas %>
    <%= form.number_field :CantidadDeBebidas, id: :pedido_CantidadDeBebidas %>
  </div>

  <div class="field">
    <%= form.label :postre %>
    <%= form.text_field :postre, id: :pedido_postre %>
  </div>

  <div class="field">
    <%= form.label :CantidadDePostres %>
    <%= form.number_field :CantidadDePostres, id: :pedido_CantidadDePostres %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pedidos/edit.html.erb
<h1>Editing Pedido</h1>

<%= render 'form', pedido: @pedido %>

<%= link_to 'Show', @pedido %> |
<%= link_to 'Back', pedidos_path %>

app/views/pedidos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pedidos</h1>

<table class="table table-sm">

  <thead>
    <tr>
      <th>Platillos</th>
      <th>Bebidas</th>
      <th>Precio</th>
      <th>Cantidaddeplatillos</th>
      <th>Cantidaddebebidas</th>
      <th>Postre</th>
      <th>Cantidaddepostres</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pedidos.each do |pedido| %>
      <tr>
        <td><%= pedido.platillos %></td>
        <td><%= pedido.bebidas %></td>
        <td><%= pedido.precio %></td>
        <td><%= pedido.CantidadDePlatillos %></td>
        <td><%= pedido.CantidadDeBebidas %></td>
        <td><%= pedido.postre %></td>
        <td><%= pedido.CantidadDePostres %></td>
        <td><%= link_to 'Show', pedido %></td>
        <td><%= link_to 'Edit', edit_pedido_path(pedido) %></td>
        <td><%= link_to 'Destroy', pedido, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pedido', pedidos_reporte_path %>

app/views/pedidos/new.html.erb
<h1>New Pedido</h1>

<%= render 'form', pedido: @pedido %>

<%= link_to 'Back', pedidos_path %>

app/views/pedidos/reporte.html.erb
 <% platillos1 = @CantidadDePlatillos.first %> 
              <% platillos2 = @CantidadDePlatillos.last %>
              <% postres1 = @CantidadDePostres.first %> 
              <% postres2 = @CantidadDePostres.last %> 
               <% bebidas1 = @CantidadDeBebidas.first %> 
              <% bebidas2 = @CantidadDeBebidas.last %> 


 <table class="table table-sm">
  <thead>
    <tr>
      <th>Platillos</th>
      <th>Bebidas</th>
      <th>Precio</th>
      <th>Cantidaddeplatillos</th>
      <th>Cantidaddebebidas</th>
      <th>Postre</th>
      <th>Cantidaddepostres</th>
    </tr>

  </thead>

  <tbody>
    <% @CantidadDePlatillos.each do |pedido| %>
      <tr>
        <td><%= pedido.platillos %></td>
        <td><%= pedido.bebidas %></td>
        <td><%= pedido.precio %></td>
        <td><%= pedido.CantidadDePlatillos %></td>
        <td><%= pedido.CantidadDeBebidas %></td>
        <td><%= pedido.postre %></td>
        <td><%= pedido.CantidadDePostres %></td>
</tr>
 <% end %> 
     
  </tbody>
</tr>
 </table>

    <table class="table table-sm">
  <thead>
    <tr>
      <th>Platillos</th>
      <th>Bebidas</th>
      <th>Precio</th>
      <th>Cantidaddeplatillos</th>
      <th>Cantidaddebebidas</th>
      <th>Postre</th>
      <th>Cantidaddepostres</th>
    </tr>

  </thead>
  <tbody>
    <% @CantidadDePostres.each do |pedido| %>
      <tr>
        <td><%= pedido.platillos %></td>
        <td><%= pedido.bebidas %></td>
        <td><%= pedido.precio %></td>
        <td><%= pedido.CantidadDePlatillos %></td>
        <td><%= pedido.CantidadDeBebidas %></td>
        <td><%= pedido.postre %></td>
        <td><%= pedido.CantidadDePostres %></td>
        </tr>
            
    <% end %>
  </tbody>
    </tr>
     </table>

     <table class="table table-sm">
  <thead>
    <tr>
      <th>Platillos</th>
      <th>Bebidas</th>
      <th>Precio</th>
      <th>Cantidaddeplatillos</th>
      <th>Cantidaddebebidas</th>
      <th>Postre</th>
      <th>Cantidaddepostres</th>
    </tr>

  </thead>
  <tbody>
    <% @CantidadDeBebidas.each do |pedido| %>
      <tr>
        <td><%= pedido.platillos %></td>
        <td><%= pedido.bebidas %></td>
        <td><%= pedido.precio %></td>
        <td><%= pedido.CantidadDePlatillos %></td>
        <td><%= pedido.CantidadDeBebidas %></td>
        <td><%= pedido.postre %></td>
        <td><%= pedido.CantidadDePostres %></td>
        </tr>
             
                  

              
    <% end %>      
      
  </tbody>
      
    </tr>
     </table>
               <h3> La bebida mas pedida es:</h3> <h4><%= bebidas1.bebidas %></h4>
              <h3> La bebida menos pedida es:</h3> <h4><%= bebidas2.bebidas%></h4>
              <h3> El platillo mas pedido es :</h3> <h4><%= platillos1.platillos %></h4>
              <h3> El platilo menos pedido es:</h3> <h4><%= platillos2.platillos %></h4> 
              <h3> El postre  mas caro es:</h3> <h4><%= postres1.postre %></h4>
              <h3> El postre mas barato es:</h3> <h4><%= postres2.postre %></h4>        

<%= link_to 'New Pedido', new_pedido_path %>

app/views/pedidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Platillos:</strong>
  <%= @pedido.platillos %>
</p>

<p>
  <strong>Bebidas:</strong>
  <%= @pedido.bebidas %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @pedido.precio %>
</p>

<p>
  <strong>Cantidaddeplatillos:</strong>
  <%= @pedido.CantidadDePlatillos %>
</p>

<p>
  <strong>Cantidaddebebidas:</strong>
  <%= @pedido.CantidadDeBebidas %>
</p>

<p>
  <strong>Postre:</strong>
  <%= @pedido.postre %>
</p>

<p>
  <strong>Cantidaddepostres:</strong>
  <%= @pedido.CantidadDePostres %>
</p>

<%= link_to 'Edit', edit_pedido_path(@pedido) %> |
<%= link_to 'Back', pedidos_path %>